version: '3.8'

services:
  frontend:
    image: rajk09/chat-app-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chat-network

  backend:
    image: rajk09/chat-app-backend:latest
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - NODE_ENV=${NODE_ENV}
    networks:
      - chat-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    networks:
      - chat-network

volumes:
  mongodb-data:

networks:
  chat-network:
    driver: bridge
